server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lol?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: kxb
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 3
    host: 192.168.31.249
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kons.entity
  configuration:
    cache-enabled: true
    aggressive-lazy-loading: true
